ALTER TABLE "blog_posts" ADD COLUMN IF NOT EXISTS "is_featured" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "tags" TEXT[] DEFAULT ARRAY[]::TEXT[];
UPDATE "news" SET "tags" = ARRAY[]::TEXT[] WHERE "tags" IS NULL;
ALTER TABLE "news" ALTER COLUMN "tags" SET NOT NULL;
ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "is_featured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "news" ADD COLUMN IF NOT EXISTS "og_image" TEXT;
