ALTER TABLE "admin_users" ADD COLUMN IF NOT EXISTS "totp_enabled" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "admin_users" ADD COLUMN IF NOT EXISTS "totp_verified_at" TIMESTAMPTZ;
ALTER TABLE "admin_users" ADD COLUMN IF NOT EXISTS "totp_backup_codes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
